#!/bin/bash

curFanSpeed=0

setFanSpeed()
{
    local minSpeed=0
    local maxSpeed=100

    local maxCoreTemp=50
    local curCoreTemp=0
    while read -r value
    do
        if [ $value -ge $curCoreTemp ]; then 
            curCoreTemp=$value
        fi        
    done <<< "$(sensors | grep "Core" | cut -f 10 -d ' ' | cut -f 2 -d '+' | cut -f 1 -d '.')"

    local intSpeed=$1
    local isValid=false
    if [[ "$intSpeed" =~ ^[0-9]+$ ]]; then
        if [[ $intSpeed -ge 20 && $intSpeed -le 100 ]]; then
            isValid=true
        fi
    fi

    # 
    if [ $isValid = false ]; then
        echo "$intSpeed is not a valid fanspeed. Valid range is 20% - 99% because my ears."; exit 1;
    fi

    if [ $curCoreTemp -gt $maxCoreTemp ]; then
        local addSpeed=$(($curCoreTemp - $maxCoreTemp))
        intSpeed=$(($intSpeed + $addSpeed + 10))
    fi

    local hexSpeed=$(printf '%x\n' $intSpeed)

    #require ipmi tools for manual fanspeed management

    if ! [ $intSpeed -eq $curFanSpeed ]; then
        #set fanspeed
        echo "MaxCore:$maxCoreTemp,CurCore:$curCoreTemp,Speed:$intSpeed,Hex:0x$hexSpeed"
         ipmitool raw 0x30 0x30 0x02 0xff $hexSpeed &>/dev/null 
        curFanSpeed=$intSpeed 
    fi
}

install()
{
     cp fanspeed /usr/local/bin/fanspeed
     chmod +x /usr/local/bin/fanspeed
}

addChronJob()
{
    #write out current crontab
    crontab -l > mycron
    #echo new cron into cron file
    echo "* * * * * bash /usr/local/bin/fanspeed 32" >> mycron
    #install new cron file
    crontab mycron
    rm mycron
}

addSystemd()
{
     cp fanspeed.service /etc/systemd/system/fanspeed.service
     systemctl start fanspeed.service 
     systemctl enable fanspeed.service
}

command -v ipmitool >/dev/null 2>&1 || { echo >&2 "I require imptool but it's not installed.  Aborting."; exit 1; }
command -v sensors >/dev/null 2>&1 || { echo >&2 "I require sensors but it's not installed.  Aborting."; exit 1; }

#enable manual fan speed control
 ipmitool raw 0x30 0x30 0x01 0x00 &>/dev/null

echo "Press [CTRL+C] to stop.."
while :; do setFanSpeed $1; sleep 1; done